name: CI

on: [push]

jobs:
  test:
    name: Run unit tests on OpenJDK ${{ matrix.jdk }}, ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [8, 11]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - run: ./gradlew test
      - if: matrix.jdk == '8' && matrix.os == 'ubuntu-latest'
        run: ./gradlew publishToMavenLocal
      - if: matrix.jdk == '8' && matrix.os == 'ubuntu-latest'
        name: Cache local maven repo
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ github.run_number }}-${{github.run_attempt }}

  integrationTest:
    needs: test
    name: Run integration tests on OpenJDK ${{ matrix.jdk }}, ${{ matrix.os }} (${{ matrix.index }}/2)
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [8]
        index: [0, 1, 2]
    runs-on: ${{ matrix.os }}
    env:
      ALL_GRADLE_VERSIONS: 2.6,2.7,2.8,2.9,2.10,2.11,2.12,2.13,2.14.1,3.0,3.1,3.2.1,3.3,3.4.1,3.5.1,4.0.2,4.1,4.2.1,4.3.1,4.4.1,4.5.1,4.6,4.7,4.8.1,4.9,4.10.3,5.0,5.1.1,5.2.1,5.3.1,5.4.1,5.5.1,5.6.4,6.0.1,6.1.1,6.2.2,6.3,6.4.1,6.5,6.9.1
      INDEX: ${{ matrix.index }}
      PARALLEL_INTEG_TEST_COUNT: 3

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
          cache: 'gradle'
      - name: Cache local maven repo
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ github.run_number }}-${{github.run_attempt }}
      - if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Couldn't restore local maven repo containing the published plugin')
      - run: ./scripts/travis-integ-tests.sh

